<template>
  <ProfileAdminSettingsModalDomainUnsubscribedDetails
    v-if="$profile.domain"
    @go-to-subscription="$emit('goToSubscription')"
  />
  <ProfileAdminSettingsModalDomainUnsubscribedSetup
    v-else
    @go-to-subscription="$emit('goToSubscription')"
  />
</template>
