#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - echo "Hello mail! I was provisioned by terraform with cloud-init."
  - timedatectl set-timezone Europe/Berlin
  - curl -sSL https://get.docker.com/ | CHANNEL=stable sh
  - systemctl enable --now docker
  - git clone https://github.com/mailcow/mailcow-dockerized /opt/mailcow

# Now on the server AFTER DNS CONFIGURATION
# cd /opt/mailcow
# ./generate_config.sh
# wait for Your IP is clean
#
# edit mailcow.conf:
# WATCHDOG_NOTIFY_EMAIL=kontakt@markus-kottlaender.de
# WATCHDOG_NOTIFY_BAN=y
# WATCHDOG_SUBJECT="Mailserver 1: "
# ACME_CONTACT=kontakt@markus-kottlaender.de
#
# echo "mail1.solihost.de" > /etc/hostname
# sed -i 's/^127\.0\.1\.1.*/127.0.1.1   mail1.solihost.de mail/' /etc/hosts
# docker compose pull
# docker compose up -d