<template>
  <ProfileAdminSettingsDomainUnsubscribedDetails
    v-if="$profile.domain"
    @go-to-subscription="$emit('goToSubscription')"
  />
  <ProfileAdminSettingsDomainUnsubscribedSetup
    v-else
    @go-to-subscription="$emit('goToSubscription')"
  />
</template>
