<template>
  <ProfileAdminDomainUnsubscribedDetails
    v-if="$profile.domain"
    @go-to-subscription="$emit('goToSubscription')"
  />
  <ProfileAdminDomainUnsubscribedSetup
    v-else
    @go-to-subscription="$emit('goToSubscription')"
  />
</template>
